### ISSUE TITLE
Problems with conditionally loaded libraries

### ISSUE THREAD

**Issue by SirVer** [fnuecke/eris#14]
Widelands contains the following conditional code:
http://bazaar.launchpad.net/~widelands-dev/widelands/trunk/view/7367/src/scripting/scripting.cc#L162

The idea behind this is debug builds of the game contain functionality that is potential unsafe, but useful for debugging. Now I have the issues though that when a debug game is saved and it should be loaded in release mode, I see the following error:

```
PANIC: unprotected error in call to Lua API (bad permanent value (no value))
```

I do not think this is a bug per se, more a search for an explanation and a suggested way forward. What can I do to make my savegames agnostic of debug/release?

**Comment by fnuecke** [comment]
That is indeed deliberate, because Eris can't (or rather shouldn't [IMHO]) decide on its own what to do if values it needs for unpersisting a state are missing, following the principle of least surprise.

If the values exposed in debug mode are all functions you can take the lazy approach: slap a `setmetatable(uperms, {__index=function()return function()end end})` on your permanent value table, automatically returning a dummy function for all missing values.

The cleaner, but more verbose approach would be to manually provide the same values you have in debug mode in the permanent value table, but have them do nothing (i.e. have all functions be dummy functions, all numbers be 0xDEADBEEF, all strings be "debug only" or something).

Alternatively, assuming that wouldn't break things left-and-right anyway, a new setting might be an option, controlling Eris' behavior on missing permanent values (error - the current behavior - or replace the value with `nil`; non-nil values would still have to be handled via `__index`, e.g.).

**Comment by SirVer** [comment]
> If the values exposed in debug mode are all functions...

They are not, they are lua tables though. But just pushing empty tables did not do the trick, the problem was the same:

~~~
lua_newtable(m_L); lua_setglobal(m_L, "package");
lua_newtable(m_L); lua_setglobal(m_L, "io");
lua_newtable(m_L); lua_setglobal(m_L, "os");
~~~

any more ideas?

**Comment by fnuecke** [comment]
Sounds very much like [what I described here](https://github.com/fnuecke/eris/issues/13#issuecomment-70921155). You'll probably have to add the actual functions to the perms table, not just the table containing them.

**Comment by SirVer** [comment]
mmh.. that is what I've thought. I decided to just remove this conditional loading of libraries. I never had any use for them in the last year anyways, so they are probably not as useful. Thanks for your explanations!
